### ISSUE TITLE
make literature coverage of demo instance clear?

### ISSUE THREAD

**Issue by jameshowison** [ourresearch/software-mentions#22]
I was sticking the names of a few tools into the demo instance, part of prepping for an OSPO proposal :)

As I did it, I imagined showing this to the maintainers of the tools; clearly the counts are large undercounts due to the limited (and bio skewed?) coverage of the papers processed.

Could we highlight that with a persistent banner across the site, reminding people of the underlying collection of PDFs that was processed?

**Comment by kermitt2** [comment]
Sure, we're talking about the software mention knowledge base browser application (https://cloud.science-miner.com/software_kb/frontend/index.html), correct? 
I already created this issue on the topic https://github.com/softcite/softcite_kb/issues/9 and I can in short term simply create a banner.

**Comment by jameshowison** [comment]
Yup, that makes sense and I see the existing issue, I'll follow that one :)
